# Generated by Django 5.0.2 on 2024-11-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=255, verbose_name='imagen')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion')),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('estado', models.CharField(max_length=21, verbose_name='Estado')),
            ],
            options={
                'db_table': 'espacios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=50, verbose_name='Nombre del metodo')),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=21, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('shorname', models.CharField(max_length=30, verbose_name='Nombre corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=120, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='HorariosDisponible',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=20, verbose_name='Día de la semana')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de cierre')),
                ('id_espacio', models.ForeignKey(db_column='id_espacio', on_delete=django.db.models.deletion.CASCADE, to='reservas.espacios')),
            ],
            options={
                'db_table': 'horarios_disponibles',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('comentarios', models.TextField()),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.espacios')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=21, verbose_name='Estado_pago')),
                ('id_metodo', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.CASCADE, to='reservas.metodospago')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='reservas.reservas')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.CharField(max_length=21, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('direccion', models.CharField(max_length=51, verbose_name='Direccion')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='reservas.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='reservas',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.usuarios'),
        ),
    ]
