# Generated by Django 5.0.2 on 2024-10-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=21, verbose_name='Telefono')),
            ],
        ),
    ]
