# Generated by Django 5.0.2 on 2024-10-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_datos'),
    ]

    operations = [
    ]
