# Generated by Django 5.0.2 on 2024-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20241023_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=21, verbose_name='Estado')),
            ],
            options={
                'db_table': 'espacios',
            },
        ),
    ]
