# Generated by Django 5.0.2 on 2024-10-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_espacios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacios',
            options={'managed': False},
        ),
    ]
